# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0633410ee0d956f3ade8e7e3578a7a3f67f39a13be1576a63d407bac33ccf72feed927bc60342c7602ba174c90d72efa7e8162cdfb08c5089bc526d2bc6beff6

test:
  secret_key_base: 66bec73aa89ae0bfe3eae7ad4bd39c05088c0d1967e2d9acc0edd1f0c38022ea553d679acf6733c703cd3830bd864557004e821c2b41d5306edca0765306911f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
